include(FetchContent)

# FIND_PACKAGE_ARGS: an installed package (find_package) wins; otherwise the source is downloaded.
# SYSTEM: the dependency's headers are system headers, so our warnings and clang-tidy skip them.
# EXCLUDE_FROM_ALL: only the parts of the dependency we link against get built.

if(MANDELBROTTER_BUILD_TESTS)
    set(INSTALL_GTEST OFF CACHE BOOL "" FORCE)
    FetchContent_Declare(googletest
        GIT_REPOSITORY https://github.com/google/googletest.git
        GIT_TAG        v1.18.0
        GIT_SHALLOW    TRUE
        SYSTEM
        EXCLUDE_FROM_ALL
        FIND_PACKAGE_ARGS NAMES GTest)
    FetchContent_MakeAvailable(googletest)
endif()

find_package(Threads REQUIRED)

# nlohmann/json (header-only). Link nlohmann_json::nlohmann_json.
set(JSON_BuildTests OFF CACHE INTERNAL "")
set(JSON_Install    OFF CACHE INTERNAL "")
FetchContent_Declare(nlohmann_json
    URL      https://github.com/nlohmann/json/releases/download/v3.12.0/json.tar.xz
    URL_HASH SHA256=42f6e95cad6ec532fd372391373363b62a14af6d771056dbfc86160e6dfff7aa
    SYSTEM
    EXCLUDE_FROM_ALL
    FIND_PACKAGE_ARGS NAMES nlohmann_json)
FetchContent_MakeAvailable(nlohmann_json)

# stb single-header libraries (stb_image_write for PNG output, stb_image for the tests).
# The repository has no CMakeLists.txt, so MakeAvailable only downloads. The implementations are compiled once
# here, in a third-party target that is deliberately NOT passed through Mandelbrotter_configure_target: it is
# vendored C code and must not be held to the project's warnings or clang-tidy checks. Link stb::stb.
FetchContent_Declare(stb
    URL      https://github.com/nothings/stb/archive/2c980bb59875b0d32144a71867fbdebb2f77cd20.tar.gz
    URL_HASH SHA256=9a955b1b49a4410088a2e0ee2a9c057c3c907d0c1d75454144cb980aca0ba515)
FetchContent_MakeAvailable(stb)
file(CONFIGURE OUTPUT ${stb_BINARY_DIR}/stb_impl.cpp CONTENT [[
// Generated by cmake/Dependencies.cmake: the single translation unit holding the stb implementations.
#define STB_IMAGE_WRITE_IMPLEMENTATION
#define STBI_WRITE_NO_STDIO
#include <stb_image_write.h>
#define STB_IMAGE_IMPLEMENTATION
#define STBI_ONLY_PNG
#define STBI_NO_STDIO
#include <stb_image.h>
]])
add_library(stb_impl STATIC EXCLUDE_FROM_ALL ${stb_BINARY_DIR}/stb_impl.cpp)
add_library(stb::stb ALIAS stb_impl)
target_include_directories(stb_impl SYSTEM PUBLIC ${stb_SOURCE_DIR})

# wxWidgets 3.2, built in-tree as static libraries on the GTK3 toolkit. Link wx::core wx::base.
# Deliberately no FIND_PACKAGE_ARGS: a *shared* system wxWidgets would otherwise be picked up, and we want a
# static, trimmed build with a known configuration. GTK itself stays a system shared library.
set(wxBUILD_SHARED     OFF  CACHE BOOL   "" FORCE)
set(wxBUILD_MONOLITHIC OFF  CACHE BOOL   "" FORCE)
set(wxBUILD_PRECOMP    OFF  CACHE STRING "" FORCE)   # precompiled headers defeat ccache
set(wxBUILD_INSTALL    OFF  CACHE BOOL   "" FORCE)
set(wxBUILD_SAMPLES    OFF  CACHE STRING "" FORCE)
set(wxBUILD_TESTS      OFF  CACHE STRING "" FORCE)
set(wxBUILD_DEMOS      OFF  CACHE BOOL   "" FORCE)
set(wxBUILD_BENCHMARKS OFF  CACHE BOOL   "" FORCE)
set(wxBUILD_LOCALES    OFF  CACHE STRING "" FORCE)
set(wxBUILD_TOOLKIT    gtk3 CACHE STRING "" FORCE)
foreach(opt wxUSE_WEBVIEW wxUSE_MEDIACTRL wxUSE_STC wxUSE_XRC wxUSE_XML wxUSE_RICHTEXT wxUSE_HTML wxUSE_PROPGRID
            wxUSE_RIBBON wxUSE_AUI wxUSE_OPENGL wxUSE_GLCANVAS_EGL wxUSE_SOUND wxUSE_LIBSDL wxUSE_LIBNOTIFY
            wxUSE_SECRETSTORE wxUSE_WEBREQUEST wxUSE_LIBMSPACK wxUSE_XTEST wxUSE_LIBLZMA wxUSE_DEBUGREPORT
            wxUSE_HELP wxUSE_WXHTML_HELP)
    set(${opt} OFF CACHE BOOL "" FORCE)
endforeach()
set(wxUSE_LIBJPEG OFF CACHE STRING "" FORCE)
set(wxUSE_LIBTIFF OFF CACHE STRING "" FORCE)
set(wxUSE_EXPAT   OFF CACHE STRING "" FORCE)
set(wxUSE_NANOSVG OFF CACHE STRING "" FORCE)
set(wxUSE_REGEX   OFF CACHE STRING "" FORCE)
set(wxUSE_LIBPNG  sys CACHE STRING "" FORCE)   # keep: wxGTK's clipboard bitmap data object is encoded as PNG
set(wxUSE_ZLIB    sys CACHE STRING "" FORCE)
FetchContent_Declare(wxwidgets
    URL      https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.11/wxWidgets-3.2.11.tar.bz2
    URL_HASH SHA256=6a129015bce2e914e4bf61ec4411854ad962801d47e92f2eb8340adb6a90af08
    SYSTEM
    EXCLUDE_FROM_ALL)
set(FETCHCONTENT_TRY_FIND_PACKAGE_MODE NEVER)
FetchContent_MakeAvailable(wxwidgets)
unset(FETCHCONTENT_TRY_FIND_PACKAGE_MODE)
