// Mandelbrotter_embed: turns any file into a C++ source that hands out its bytes, so the help book
// can live inside the executable.
//
//   Mandelbrotter_embed <input> <output.cpp> <header-to-include> <namespace> <function>
//
// The bytes are emitted as string literals of at most kChunkBytes each (MSVC caps a single literal
// at 16380 bytes), printable ASCII as is and everything else as three-digit octal escapes, which a
// following digit cannot extend. Compilers handle string literals far faster than brace-initialised
// byte arrays of the same size. The output is only replaced when its content changes, so an
// unchanged book does not recompile.
#include <algorithm>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <exception>
#include <filesystem>
#include <fstream>
#include <ios>
#include <iterator>
#include <print>
#include <span>
#include <sstream>
#include <string>
#include <string_view>
#include <vector>

namespace
{

constexpr std::size_t kChunkBytes = 8192;
constexpr std::size_t kLineBytes  = 64;

std::vector<unsigned char> readAll(const std::filesystem::path& path)
{
    std::ifstream in(path, std::ios::binary);
    if (!in)
    {
        throw std::ios_base::failure("cannot read " + path.string());
    }
    return {std::istreambuf_iterator<char>(in), std::istreambuf_iterator<char>()};
}

std::string escaped(std::span<const unsigned char> bytes)
{
    std::string out;
    out.reserve(bytes.size() * 4);
    for (const unsigned char byte : bytes)
    {
        const bool plain =
            byte >= 0x20 && byte < 0x7f && byte != '"' && byte != '\\' && byte != '?';
        if (plain)
        {
            out.push_back(static_cast<char>(byte));
        }
        else
        {
            out.push_back('\\');
            out.push_back(static_cast<char>('0' + ((byte >> 6) & 7U)));
            out.push_back(static_cast<char>('0' + ((byte >> 3) & 7U)));
            out.push_back(static_cast<char>('0' + (byte & 7U)));
        }
    }
    return out;
}

std::string generate(std::span<const unsigned char> data, std::string_view inputName,
                     std::string_view header, std::string_view ns, std::string_view function)
{
    std::ostringstream out;
    std::println(out, "// Generated by Mandelbrotter_embed from {}. Do not edit.", inputName);
    std::println(out, "#include <array>");
    std::println(out, "#include <span>");
    std::println(out, "#include <string_view>");
    std::println(out, "");
    std::println(out, "#include \"{}\"", header);
    std::println(out, "");
    std::println(out, "namespace {}", ns);
    std::println(out, "{{");
    std::println(out, "");
    std::println(out, "namespace");
    std::println(out, "{{");
    std::println(out, "");
    if (data.empty())
    {
        std::println(out, "constexpr std::array<std::string_view, 0> kChunks{{}};");
    }
    else
    {
        std::println(out, "constexpr std::array kChunks{{");
        for (std::size_t offset = 0; offset < data.size(); offset += kChunkBytes)
        {
            const auto chunk = data.subspan(offset, std::min(kChunkBytes, data.size() - offset));
            std::println(out, "    std::string_view(");
            for (std::size_t line = 0; line < chunk.size(); line += kLineBytes)
            {
                std::println(
                    out, "        \"{}\"",
                    escaped(chunk.subspan(line, std::min(kLineBytes, chunk.size() - line))));
            }
            std::println(out, "        , {}),", chunk.size());
        }
        std::println(out, "}};");
    }
    std::println(out, "");
    std::println(out, "}}  // namespace");
    std::println(out, "");
    std::println(out, "std::span<const std::string_view> {}() noexcept", function);
    std::println(out, "{{");
    std::println(out, "    return kChunks;");
    std::println(out, "}}");
    std::println(out, "");
    std::println(out, "}}  // namespace {}", ns);
    return out.str();
}

bool sameContent(const std::filesystem::path& path, const std::string& content)
{
    std::ifstream in(path, std::ios::binary);
    if (!in)
    {
        return false;
    }
    const std::string existing{std::istreambuf_iterator<char>(in),
                               std::istreambuf_iterator<char>()};
    return existing == content;
}

int run(std::span<char*> args)
{
    if (args.size() != 6)
    {
        std::println(stderr,
                     "usage: {} <input> <output.cpp> <header-to-include> <namespace> <function>",
                     args.empty() ? "Mandelbrotter_embed" : args[0]);
        return 2;
    }
    const std::filesystem::path input(args[1]);
    const std::filesystem::path output(args[2]);
    const std::string           content =
        generate(readAll(input), input.filename().string(), args[3], args[4], args[5]);
    if (sameContent(output, content))
    {
        return 0;
    }
    std::filesystem::create_directories(output.parent_path());
    const std::filesystem::path temporary = output.string() + ".tmp";
    {
        std::ofstream out(temporary, std::ios::binary | std::ios::trunc);
        out << content;
        if (!out)
        {
            throw std::ios_base::failure("cannot write " + temporary.string());
        }
    }
    std::filesystem::rename(temporary, output);
    return 0;
}

}  // namespace

int main(int argc, char** argv)
{
    try
    {
        return run(std::span<char*>(argv, static_cast<std::size_t>(argc)));
    }
    catch (const std::exception& e)
    {
        // C stdio only: nothing here may throw.
        std::fputs("Mandelbrotter_embed: ", stderr);
        std::fputs(e.what(), stderr);
        std::fputs("\n", stderr);
        return 1;
    }
    catch (...)
    {
        std::fputs("Mandelbrotter_embed: unknown error\n", stderr);
        return 1;
    }
}
