// Mandelbrotter_embed: turns any file into a C++ source that hands out its bytes, so the help book
// can live inside the executable.
//
//   Mandelbrotter_embed <input> <output.cpp> <header-to-include> <namespace> <function>
//
// The bytes are emitted as string literals of at most kChunkBytes each (MSVC caps a single literal
// at 16380 bytes), printable ASCII as is and everything else as three-digit octal escapes; a digit
// that follows an escape is escaped as well, so no compiler can misread the sequence. Compilers
// handle string literals far faster than brace-initialised byte arrays of the same size. The output
// is only replaced when its content changes, so an unchanged book does not recompile.
#include <algorithm>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <exception>
#include <filesystem>
#include <format>
#include <fstream>
#include <ios>
#include <iterator>
#include <print>
#include <span>
#include <sstream>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace
{

constexpr std::size_t kChunkBytes = 8192;
constexpr std::size_t kLineBytes  = 64;

/// One line of generated source. Apple's libc++ has no std::println for streams, so this stands in
/// for it (and wins overload resolution against std's where that exists, by the exact stream type).
template <typename... Args>
void println(std::ostringstream& out, std::format_string<Args...> format, Args&&... args)
{
    out << std::format(format, std::forward<Args>(args)...) << '\n';
}

std::vector<unsigned char> readAll(const std::filesystem::path& path)
{
    std::ifstream in(path, std::ios::binary);
    if (!in)
    {
        throw std::ios_base::failure("cannot read " + path.string());
    }
    return {std::istreambuf_iterator<char>(in), std::istreambuf_iterator<char>()};
}

std::string escaped(std::span<const unsigned char> bytes)
{
    std::string out;
    out.reserve(bytes.size() * 4);
    bool afterEscape = false;
    for (const unsigned char byte : bytes)
    {
        // A digit right after an octal escape is escaped too: the escape is complete after three
        // digits, but MSVC warns about the sequence (C4125).
        const bool digit = byte >= '0' && byte <= '9';
        const bool plain = byte >= 0x20 && byte < 0x7f && byte != '"' && byte != '\\' &&
                           byte != '?' && !(digit && afterEscape);
        if (plain)
        {
            out.push_back(static_cast<char>(byte));
        }
        else
        {
            out.push_back('\\');
            out.push_back(static_cast<char>('0' + ((byte >> 6) & 7U)));
            out.push_back(static_cast<char>('0' + ((byte >> 3) & 7U)));
            out.push_back(static_cast<char>('0' + (byte & 7U)));
        }
        afterEscape = !plain;
    }
    return out;
}

std::string generate(std::span<const unsigned char> data, std::string_view inputName,
                     std::string_view header, std::string_view ns, std::string_view function)
{
    std::ostringstream out;
    println(out, "// Generated by Mandelbrotter_embed from {}. Do not edit.", inputName);
    println(out, "#include <array>");
    println(out, "#include <span>");
    println(out, "#include <string_view>");
    println(out, "");
    println(out, "#include \"{}\"", header);
    println(out, "");
    println(out, "namespace {}", ns);
    println(out, "{{");
    println(out, "");
    println(out, "namespace");
    println(out, "{{");
    println(out, "");
    // The count is spelled out: deducing it instantiates a fold expression over every chunk, which
    // exceeds Clang's default nesting limit of 256 once the book passes about 2 MB.
    const std::size_t chunkCount = (data.size() + kChunkBytes - 1) / kChunkBytes;
    println(out, "constexpr std::array<std::string_view, {}> kChunks{{", chunkCount);
    for (std::size_t offset = 0; offset < data.size(); offset += kChunkBytes)
    {
        const auto chunk = data.subspan(offset, std::min(kChunkBytes, data.size() - offset));
        println(out, "    std::string_view(");
        for (std::size_t start = 0; start < chunk.size(); start += kLineBytes)
        {
            println(out, "        \"{}\"",
                    escaped(chunk.subspan(start, std::min(kLineBytes, chunk.size() - start))));
        }
        println(out, "        , {}),", chunk.size());
    }
    println(out, "}};");
    println(out, "");
    println(out, "}}  // namespace");
    println(out, "");
    println(out, "std::span<const std::string_view> {}() noexcept", function);
    println(out, "{{");
    println(out, "    return kChunks;");
    println(out, "}}");
    println(out, "");
    println(out, "}}  // namespace {}", ns);
    return out.str();
}

bool sameContent(const std::filesystem::path& path, const std::string& content)
{
    std::ifstream in(path, std::ios::binary);
    if (!in)
    {
        return false;
    }
    const std::string existing{std::istreambuf_iterator<char>(in),
                               std::istreambuf_iterator<char>()};
    return existing == content;
}

int run(std::span<char*> args)
{
    if (args.size() != 6)
    {
        std::println(stderr,
                     "usage: {} <input> <output.cpp> <header-to-include> <namespace> <function>",
                     args.empty() ? "Mandelbrotter_embed" : args[0]);
        return 2;
    }
    const std::filesystem::path input(args[1]);
    const std::filesystem::path output(args[2]);
    const std::string           content =
        generate(readAll(input), input.filename().string(), args[3], args[4], args[5]);
    if (sameContent(output, content))
    {
        return 0;
    }
    std::filesystem::create_directories(output.parent_path());
    const std::filesystem::path temporary = output.string() + ".tmp";
    {
        std::ofstream out(temporary, std::ios::binary | std::ios::trunc);
        out << content;
        if (!out)
        {
            throw std::ios_base::failure("cannot write " + temporary.string());
        }
    }
    std::filesystem::rename(temporary, output);
    return 0;
}

}  // namespace

int main(int argc, char** argv)
{
    try
    {
        return run(std::span<char*>(argv, static_cast<std::size_t>(argc)));
    }
    catch (const std::exception& e)
    {
        // C stdio only: nothing here may throw.
        std::fputs("Mandelbrotter_embed: ", stderr);
        std::fputs(e.what(), stderr);
        std::fputs("\n", stderr);
        return 1;
    }
    catch (...)
    {
        std::fputs("Mandelbrotter_embed: unknown error\n", stderr);
        return 1;
    }
}
